name: Codacy Analysis CLI

on: 
  push: 
    branches:
      - master  # Trigger on pushes to master

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Latest stable version for checkout action

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master  # Switch to master branch of Codacy CLI
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}  # Ensure the secret is set correctly
